spring:
  jackson:
    default-property-inclusion: non_null
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

  data:
    mongodb:
      database: keeper
      port: 27017
      host: localhost
logging:
  level:
    org.springframework.security: WARN
    org.springframework.data.mongodb.core.MongoTemplate: WARN
server:
  port: 8082
filer:
  url: http://files-keeper/